# Basic Site Settings
title: "Eric Vero, PhD"
description: "Digital Historian of Disability & Fandom // Author"
url: "https://eaverowrites.com"
baseurl: ""
repository: eaverowrites/eaverowrites.github.io
remote_theme: alshedivat/al-folio

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc
  - jemoji

# Biographic Info
first_name: Eric
last_name: Vero
middle_name: A.
address: "Woodstock, ON"
email: eaverowrites@gmail.com

# Social Links
social: true # Add this line to tell the theme to enable the social section
github_username: eavero
orcid_id: "0009-0009-9497-153X"

# Theme Layout Settings
navbar_fixed: true
footer_fixed: false
