# Basic Site Settings
title: "Eric Vero, PhD"
description: "Digital Historian of Disability & Fandom // Author"
url: "https://eaverowrites.com"
baseurl: ""
repository: eavero/eavero.github.io
remote_theme: alshedivat/al-folio

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-twitter-plugin
  - jekyll-toc
  - jekyll-remote-theme

# Biographic Info (Used by al-folio)
first_name: Eric
last_name: Vero
middle_name: A.
address: "Woodstock, ON"
email: eaverowrites@gmail.com

# Social Links
github_username: eavero
googlescholar_id: PS_CX0AAAAAJ
orcid_id: "0009-0009-9497-153X" # Replace with your actual ID

# Theme Layout Settings
navbar_fixed: true
footer_fixed: false
